/**
 * GENERATED by scripts/gen_languages.mjs — do not edit by hand.
 *
 * 63 languages (one per Ant Design locale). Antd locale objects and
 * dictionaries are loaded through dynamic imports so each language is its own
 * chunk: only the active language plus the English fallback are ever fetched.
 */
import type { Locale } from 'antd/es/locale';

export interface LangOption {
  /** Tag persisted in localStorage, e.g. `zh-TW`. */
  value: string;
  /** Endonym shown in the picker (from Intl.DisplayNames, never hand-written). */
  label: string;
  /** English name for logs and coverage reports. */
  english: string;
  /** dayjs locale code for date/relative-time formatting. */
  dayjs: string;
  dir: 'ltr' | 'rtl';
  /** Lazily load the antd component locale + this language's dictionary. */
  load: () => Promise<{ antd: Locale; dict: Record<string, string> }>;
  /** Lazily register the dayjs locale (date pickers, "3 hours ago"). */
  dayjsLoad: () => Promise<unknown>;
}

const load = (
  antd: () => Promise<{ default: Locale }>,
  dict: () => Promise<{ dict: Record<string, string> }>,
) => async () => {
  const [a, d] = await Promise.all([antd(), dict()]);
  return { antd: a.default, dict: d.dict };
};

export const LANGS: LangOption[] = [
  {
    value: 'ar-EG', label: "العربية", english: "Arabic",
    dayjs: 'ar', dir: 'rtl',
    load: load(() => import('antd/locale/ar_EG'), () => import('./locales/ar-EG')),
    dayjsLoad: () => import('dayjs/locale/ar'),
  },
  {
    value: 'az-AZ', label: "azərbaycan", english: "Azerbaijani",
    dayjs: 'az', dir: 'ltr',
    load: load(() => import('antd/locale/az_AZ'), () => import('./locales/az-AZ')),
    dayjsLoad: () => import('dayjs/locale/az'),
  },
  {
    value: 'bg-BG', label: "български", english: "Bulgarian",
    dayjs: 'bg', dir: 'ltr',
    load: load(() => import('antd/locale/bg_BG'), () => import('./locales/bg-BG')),
    dayjsLoad: () => import('dayjs/locale/bg'),
  },
  {
    value: 'bn-BD', label: "বাংলা", english: "Bangla",
    dayjs: 'bn-bd', dir: 'ltr',
    load: load(() => import('antd/locale/bn_BD'), () => import('./locales/bn-BD')),
    dayjsLoad: () => import('dayjs/locale/bn-bd'),
  },
  {
    value: 'by-BY', label: "by", english: "by",
    dayjs: 'en', dir: 'ltr',
    load: load(() => import('antd/locale/by_BY'), () => import('./locales/by-BY')),
    dayjsLoad: () => import('dayjs/locale/en'),
  },
  {
    value: 'ca-ES', label: "català", english: "Catalan",
    dayjs: 'ca', dir: 'ltr',
    load: load(() => import('antd/locale/ca_ES'), () => import('./locales/ca-ES')),
    dayjsLoad: () => import('dayjs/locale/ca'),
  },
  {
    value: 'cs-CZ', label: "čeština", english: "Czech",
    dayjs: 'cs', dir: 'ltr',
    load: load(() => import('antd/locale/cs_CZ'), () => import('./locales/cs-CZ')),
    dayjsLoad: () => import('dayjs/locale/cs'),
  },
  {
    value: 'da-DK', label: "dansk", english: "Danish",
    dayjs: 'da', dir: 'ltr',
    load: load(() => import('antd/locale/da_DK'), () => import('./locales/da-DK')),
    dayjsLoad: () => import('dayjs/locale/da'),
  },
  {
    value: 'de-DE', label: "Deutsch", english: "German",
    dayjs: 'de', dir: 'ltr',
    load: load(() => import('antd/locale/de_DE'), () => import('./locales/de-DE')),
    dayjsLoad: () => import('dayjs/locale/de'),
  },
  {
    value: 'el-GR', label: "Ελληνικά", english: "Greek",
    dayjs: 'el', dir: 'ltr',
    load: load(() => import('antd/locale/el_GR'), () => import('./locales/el-GR')),
    dayjsLoad: () => import('dayjs/locale/el'),
  },
  {
    value: 'en-US', label: "English", english: "English",
    dayjs: 'en', dir: 'ltr',
    load: load(() => import('antd/locale/en_US'), () => import('./locales/en-US')),
    dayjsLoad: () => import('dayjs/locale/en'),
  },
  {
    value: 'es-ES', label: "español", english: "Spanish",
    dayjs: 'es', dir: 'ltr',
    load: load(() => import('antd/locale/es_ES'), () => import('./locales/es-ES')),
    dayjsLoad: () => import('dayjs/locale/es'),
  },
  {
    value: 'et-EE', label: "eesti", english: "Estonian",
    dayjs: 'et', dir: 'ltr',
    load: load(() => import('antd/locale/et_EE'), () => import('./locales/et-EE')),
    dayjsLoad: () => import('dayjs/locale/et'),
  },
  {
    value: 'eu-ES', label: "euskara", english: "Basque",
    dayjs: 'eu', dir: 'ltr',
    load: load(() => import('antd/locale/eu_ES'), () => import('./locales/eu-ES')),
    dayjsLoad: () => import('dayjs/locale/eu'),
  },
  {
    value: 'fa-IR', label: "فارسی", english: "Persian",
    dayjs: 'fa', dir: 'rtl',
    load: load(() => import('antd/locale/fa_IR'), () => import('./locales/fa-IR')),
    dayjsLoad: () => import('dayjs/locale/fa'),
  },
  {
    value: 'fi-FI', label: "suomi", english: "Finnish",
    dayjs: 'fi', dir: 'ltr',
    load: load(() => import('antd/locale/fi_FI'), () => import('./locales/fi-FI')),
    dayjsLoad: () => import('dayjs/locale/fi'),
  },
  {
    value: 'fr-FR', label: "français", english: "French",
    dayjs: 'fr', dir: 'ltr',
    load: load(() => import('antd/locale/fr_FR'), () => import('./locales/fr-FR')),
    dayjsLoad: () => import('dayjs/locale/fr'),
  },
  {
    value: 'ga-IE', label: "Gaeilge", english: "Irish",
    dayjs: 'ga', dir: 'ltr',
    load: load(() => import('antd/locale/ga_IE'), () => import('./locales/ga-IE')),
    dayjsLoad: () => import('dayjs/locale/ga'),
  },
  {
    value: 'gl-ES', label: "galego", english: "Galician",
    dayjs: 'gl', dir: 'ltr',
    load: load(() => import('antd/locale/gl_ES'), () => import('./locales/gl-ES')),
    dayjsLoad: () => import('dayjs/locale/gl'),
  },
  {
    value: 'he-IL', label: "עברית", english: "Hebrew",
    dayjs: 'he', dir: 'rtl',
    load: load(() => import('antd/locale/he_IL'), () => import('./locales/he-IL')),
    dayjsLoad: () => import('dayjs/locale/he'),
  },
  {
    value: 'hi-IN', label: "हिन्दी", english: "Hindi",
    dayjs: 'hi', dir: 'ltr',
    load: load(() => import('antd/locale/hi_IN'), () => import('./locales/hi-IN')),
    dayjsLoad: () => import('dayjs/locale/hi'),
  },
  {
    value: 'hr-HR', label: "hrvatski", english: "Croatian",
    dayjs: 'hr', dir: 'ltr',
    load: load(() => import('antd/locale/hr_HR'), () => import('./locales/hr-HR')),
    dayjsLoad: () => import('dayjs/locale/hr'),
  },
  {
    value: 'hu-HU', label: "magyar", english: "Hungarian",
    dayjs: 'hu', dir: 'ltr',
    load: load(() => import('antd/locale/hu_HU'), () => import('./locales/hu-HU')),
    dayjsLoad: () => import('dayjs/locale/hu'),
  },
  {
    value: 'hy-AM', label: "հայերեն", english: "Armenian",
    dayjs: 'hy-am', dir: 'ltr',
    load: load(() => import('antd/locale/hy_AM'), () => import('./locales/hy-AM')),
    dayjsLoad: () => import('dayjs/locale/hy-am'),
  },
  {
    value: 'id-ID', label: "Indonesia", english: "Indonesian",
    dayjs: 'id', dir: 'ltr',
    load: load(() => import('antd/locale/id_ID'), () => import('./locales/id-ID')),
    dayjsLoad: () => import('dayjs/locale/id'),
  },
  {
    value: 'is-IS', label: "íslenska", english: "Icelandic",
    dayjs: 'is', dir: 'ltr',
    load: load(() => import('antd/locale/is_IS'), () => import('./locales/is-IS')),
    dayjsLoad: () => import('dayjs/locale/is'),
  },
  {
    value: 'it-IT', label: "italiano", english: "Italian",
    dayjs: 'it', dir: 'ltr',
    load: load(() => import('antd/locale/it_IT'), () => import('./locales/it-IT')),
    dayjsLoad: () => import('dayjs/locale/it'),
  },
  {
    value: 'ja-JP', label: "日本語", english: "Japanese",
    dayjs: 'ja', dir: 'ltr',
    load: load(() => import('antd/locale/ja_JP'), () => import('./locales/ja-JP')),
    dayjsLoad: () => import('dayjs/locale/ja'),
  },
  {
    value: 'ka-GE', label: "ქართული", english: "Georgian",
    dayjs: 'ka', dir: 'ltr',
    load: load(() => import('antd/locale/ka_GE'), () => import('./locales/ka-GE')),
    dayjsLoad: () => import('dayjs/locale/ka'),
  },
  {
    value: 'kk-KZ', label: "қазақ тілі", english: "Kazakh",
    dayjs: 'kk', dir: 'ltr',
    load: load(() => import('antd/locale/kk_KZ'), () => import('./locales/kk-KZ')),
    dayjsLoad: () => import('dayjs/locale/kk'),
  },
  {
    value: 'km-KH', label: "ខ្មែរ", english: "Khmer",
    dayjs: 'km', dir: 'ltr',
    load: load(() => import('antd/locale/km_KH'), () => import('./locales/km-KH')),
    dayjsLoad: () => import('dayjs/locale/km'),
  },
  {
    value: 'kmr-IQ', label: "ku", english: "Kurdish",
    dayjs: 'en', dir: 'ltr',
    load: load(() => import('antd/locale/kmr_IQ'), () => import('./locales/kmr-IQ')),
    dayjsLoad: () => import('dayjs/locale/en'),
  },
  {
    value: 'kn-IN', label: "ಕನ್ನಡ", english: "Kannada",
    dayjs: 'kn', dir: 'ltr',
    load: load(() => import('antd/locale/kn_IN'), () => import('./locales/kn-IN')),
    dayjsLoad: () => import('dayjs/locale/kn'),
  },
  {
    value: 'ko-KR', label: "한국어", english: "Korean",
    dayjs: 'ko', dir: 'ltr',
    load: load(() => import('antd/locale/ko_KR'), () => import('./locales/ko-KR')),
    dayjsLoad: () => import('dayjs/locale/ko'),
  },
  {
    value: 'ku-IQ', label: "ku", english: "Kurdish",
    dayjs: 'ku', dir: 'rtl',
    load: load(() => import('antd/locale/ku_IQ'), () => import('./locales/ku-IQ')),
    dayjsLoad: () => import('dayjs/locale/ku'),
  },
  {
    value: 'lt-LT', label: "lietuvių", english: "Lithuanian",
    dayjs: 'lt', dir: 'ltr',
    load: load(() => import('antd/locale/lt_LT'), () => import('./locales/lt-LT')),
    dayjsLoad: () => import('dayjs/locale/lt'),
  },
  {
    value: 'lv-LV', label: "latviešu", english: "Latvian",
    dayjs: 'lv', dir: 'ltr',
    load: load(() => import('antd/locale/lv_LV'), () => import('./locales/lv-LV')),
    dayjsLoad: () => import('dayjs/locale/lv'),
  },
  {
    value: 'mk-MK', label: "македонски", english: "Macedonian",
    dayjs: 'mk', dir: 'ltr',
    load: load(() => import('antd/locale/mk_MK'), () => import('./locales/mk-MK')),
    dayjsLoad: () => import('dayjs/locale/mk'),
  },
  {
    value: 'ml-IN', label: "മലയാളം", english: "Malayalam",
    dayjs: 'ml', dir: 'ltr',
    load: load(() => import('antd/locale/ml_IN'), () => import('./locales/ml-IN')),
    dayjsLoad: () => import('dayjs/locale/ml'),
  },
  {
    value: 'mn-MN', label: "монгол", english: "Mongolian",
    dayjs: 'mn', dir: 'ltr',
    load: load(() => import('antd/locale/mn_MN'), () => import('./locales/mn-MN')),
    dayjsLoad: () => import('dayjs/locale/mn'),
  },
  {
    value: 'ms-MY', label: "Melayu", english: "Malay",
    dayjs: 'ms-my', dir: 'ltr',
    load: load(() => import('antd/locale/ms_MY'), () => import('./locales/ms-MY')),
    dayjsLoad: () => import('dayjs/locale/ms-my'),
  },
  {
    value: 'my-MM', label: "မြန်မာ", english: "Burmese",
    dayjs: 'my', dir: 'ltr',
    load: load(() => import('antd/locale/my_MM'), () => import('./locales/my-MM')),
    dayjsLoad: () => import('dayjs/locale/my'),
  },
  {
    value: 'nb-NO', label: "norsk bokmål", english: "Norwegian Bokmål",
    dayjs: 'nb', dir: 'ltr',
    load: load(() => import('antd/locale/nb_NO'), () => import('./locales/nb-NO')),
    dayjsLoad: () => import('dayjs/locale/nb'),
  },
  {
    value: 'ne-NP', label: "नेपाली", english: "Nepali",
    dayjs: 'ne', dir: 'ltr',
    load: load(() => import('antd/locale/ne_NP'), () => import('./locales/ne-NP')),
    dayjsLoad: () => import('dayjs/locale/ne'),
  },
  {
    value: 'nl-NL', label: "Nederlands", english: "Dutch",
    dayjs: 'nl', dir: 'ltr',
    load: load(() => import('antd/locale/nl_NL'), () => import('./locales/nl-NL')),
    dayjsLoad: () => import('dayjs/locale/nl'),
  },
  {
    value: 'pl-PL', label: "polski", english: "Polish",
    dayjs: 'pl', dir: 'ltr',
    load: load(() => import('antd/locale/pl_PL'), () => import('./locales/pl-PL')),
    dayjsLoad: () => import('dayjs/locale/pl'),
  },
  {
    value: 'pt-BR', label: "português", english: "Portuguese",
    dayjs: 'pt-br', dir: 'ltr',
    load: load(() => import('antd/locale/pt_BR'), () => import('./locales/pt-BR')),
    dayjsLoad: () => import('dayjs/locale/pt-br'),
  },
  {
    value: 'ro-RO', label: "română", english: "Romanian",
    dayjs: 'ro', dir: 'ltr',
    load: load(() => import('antd/locale/ro_RO'), () => import('./locales/ro-RO')),
    dayjsLoad: () => import('dayjs/locale/ro'),
  },
  {
    value: 'ru-RU', label: "русский", english: "Russian",
    dayjs: 'ru', dir: 'ltr',
    load: load(() => import('antd/locale/ru_RU'), () => import('./locales/ru-RU')),
    dayjsLoad: () => import('dayjs/locale/ru'),
  },
  {
    value: 'si-LK', label: "සිංහල", english: "Sinhala",
    dayjs: 'si', dir: 'ltr',
    load: load(() => import('antd/locale/si_LK'), () => import('./locales/si-LK')),
    dayjsLoad: () => import('dayjs/locale/si'),
  },
  {
    value: 'sk-SK', label: "slovenčina", english: "Slovak",
    dayjs: 'sk', dir: 'ltr',
    load: load(() => import('antd/locale/sk_SK'), () => import('./locales/sk-SK')),
    dayjsLoad: () => import('dayjs/locale/sk'),
  },
  {
    value: 'sl-SI', label: "slovenščina", english: "Slovenian",
    dayjs: 'sl', dir: 'ltr',
    load: load(() => import('antd/locale/sl_SI'), () => import('./locales/sl-SI')),
    dayjsLoad: () => import('dayjs/locale/sl'),
  },
  {
    value: 'sr-RS', label: "српски", english: "Serbian",
    dayjs: 'sr', dir: 'ltr',
    load: load(() => import('antd/locale/sr_RS'), () => import('./locales/sr-RS')),
    dayjsLoad: () => import('dayjs/locale/sr'),
  },
  {
    value: 'sv-SE', label: "svenska", english: "Swedish",
    dayjs: 'sv', dir: 'ltr',
    load: load(() => import('antd/locale/sv_SE'), () => import('./locales/sv-SE')),
    dayjsLoad: () => import('dayjs/locale/sv'),
  },
  {
    value: 'ta-IN', label: "தமிழ்", english: "Tamil",
    dayjs: 'ta', dir: 'ltr',
    load: load(() => import('antd/locale/ta_IN'), () => import('./locales/ta-IN')),
    dayjsLoad: () => import('dayjs/locale/ta'),
  },
  {
    value: 'th-TH', label: "ไทย", english: "Thai",
    dayjs: 'th', dir: 'ltr',
    load: load(() => import('antd/locale/th_TH'), () => import('./locales/th-TH')),
    dayjsLoad: () => import('dayjs/locale/th'),
  },
  {
    value: 'tk-TK', label: "türkmen dili", english: "Turkmen",
    dayjs: 'tk', dir: 'ltr',
    load: load(() => import('antd/locale/tk_TK'), () => import('./locales/tk-TK')),
    dayjsLoad: () => import('dayjs/locale/tk'),
  },
  {
    value: 'tr-TR', label: "Türkçe", english: "Turkish",
    dayjs: 'tr', dir: 'ltr',
    load: load(() => import('antd/locale/tr_TR'), () => import('./locales/tr-TR')),
    dayjsLoad: () => import('dayjs/locale/tr'),
  },
  {
    value: 'uk-UA', label: "українська", english: "Ukrainian",
    dayjs: 'uk', dir: 'ltr',
    load: load(() => import('antd/locale/uk_UA'), () => import('./locales/uk-UA')),
    dayjsLoad: () => import('dayjs/locale/uk'),
  },
  {
    value: 'ur-PK', label: "اردو", english: "Urdu",
    dayjs: 'ur', dir: 'rtl',
    load: load(() => import('antd/locale/ur_PK'), () => import('./locales/ur-PK')),
    dayjsLoad: () => import('dayjs/locale/ur'),
  },
  {
    value: 'uz-UZ', label: "o‘zbek", english: "Uzbek",
    dayjs: 'uz', dir: 'ltr',
    load: load(() => import('antd/locale/uz_UZ'), () => import('./locales/uz-UZ')),
    dayjsLoad: () => import('dayjs/locale/uz'),
  },
  {
    value: 'vi-VN', label: "Tiếng Việt", english: "Vietnamese",
    dayjs: 'vi', dir: 'ltr',
    load: load(() => import('antd/locale/vi_VN'), () => import('./locales/vi-VN')),
    dayjsLoad: () => import('dayjs/locale/vi'),
  },
  {
    value: 'zh-CN', label: "中文", english: "Chinese",
    dayjs: 'zh-cn', dir: 'ltr',
    load: load(() => import('antd/locale/zh_CN'), () => import('./locales/zh-CN')),
    dayjsLoad: () => import('dayjs/locale/zh-cn'),
  },
];

export const DEFAULT_LANG = 'en-US';

/** Resolve a browser tag against the available set (zh-Hans-CN → zh-CN). */
export function matchLang(tag: string | undefined | null): string | undefined {
  if (!tag) return undefined;
  const norm = tag.replace(/_/g, '-').toLowerCase();
  const exact = LANGS.find((l) => l.value.toLowerCase() === norm);
  if (exact) return exact.value;
  const base = norm.split('-')[0];
  return LANGS.find((l) => l.value.toLowerCase().split('-')[0] === base)?.value;
}

export const isRTL = (value: string) =>
  LANGS.find((l) => l.value === value)?.dir === 'rtl';
