/**
 * Generate the language table for the i18n runtime (v2).
 *
 * 70 real Ant Design locales (its `locale/` dir also holds internal files
 * `context.js` / `useLocale.js`, which are NOT languages).  Everything is
 * loaded lazily — the antd locale object and the dictionary each become their
 * own Vite chunk, so shipping 70 languages does not bloat the initial bundle:
 * only the active language (plus the en fallback) is ever fetched.
 *
 * Emits:
 *   web/src/i18n/languages.ts   (imported by src/i18n/index.tsx)
 *   .agn_tmp/languages.json     (consumed by scripts/merge_i18n.py)
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Repo root = the parent of this script's directory, so the generator works
// from any checkout (it used to hardcode the author's E:\ path).
const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ANTD = path.join(REPO, 'web/node_modules/antd/locale');
const DAYJS = path.join(REPO, 'web/node_modules/dayjs/locale');

const NOT_LANGUAGES = new Set(['context', 'useLocale', 'index']);
const RTL_LANGS = new Set(['ar', 'he', 'fa', 'ur', 'ckb', 'ku', 'dv', 'ps', 'sd', 'yi']);

/**
 * One locale per language.
 *
 * Variants of the same language (en-GB vs en-US, fr-CA vs fr-FR, zh-TW vs
 * zh-CN) produce near-identical copy and only differ in date/measurement or
 * script conventions, so the product ships a single primary per language.
 * `PRIMARY` names the keeper; anything else sharing that language subtag is
 * dropped. Put a locale code in `KEEP_VARIANTS` to bring one back (e.g.
 * 'zh_TW' to also ship Traditional Chinese).
 */
const KEEP_VARIANTS = new Set([]);
const PRIMARY = {
  en: 'en_US',
  fr: 'fr_FR',
  zh: 'zh_CN',
  pt: 'pt_BR',
  nl: 'nl_NL',
};

const dayjsLocales = new Set(
  fs.readdirSync(DAYJS).filter((f) => f.endsWith('.js') && f !== 'index.js')
    .map((f) => f.replace(/\.js$/, '')),
);

function pickDayjs(code) {
  const parts = code.toLowerCase().split('_');
  for (const c of [parts.join('-'), parts.join(''), parts[0]]) {
    if (dayjsLocales.has(c)) return c;
  }
  return 'en';
}

const displayName = (locale, lang) => {
  try {
    return new Intl.DisplayNames([locale], { type: 'language' }).of(lang);
  } catch {
    return undefined;
  }
};

const rows = fs.readdirSync(ANTD)
  .filter((f) => f.endsWith('.js'))
  .map((f) => f.replace(/\.js$/, ''))
  .filter((code) => !NOT_LANGUAGES.has(code))
  .sort()
  .filter((code) => {
    const lang = code.split('_')[0];
    const all = fs.readdirSync(ANTD)
      .filter((f) => f.endsWith('.js'))
      .map((f) => f.replace(/\.js$/, ''))
      .filter((c) => !NOT_LANGUAGES.has(c) && c.split('_')[0] === lang);
    if (all.length < 2) return true;                 // single locale for this language
    if (KEEP_VARIANTS.has(code)) return true;        // explicitly kept variant
    return code === (PRIMARY[lang] ?? all.sort()[0]);
  })
  .map((code) => {
    const lang = code.split('_')[0];
    const value = code.replace('_', '-');
    const label = displayName(value, lang) || displayName(lang, lang) || value;
    const english = displayName('en', lang) || value;
    return { antd: code, value, label, english, dayjs: pickDayjs(code),
             dir: RTL_LANGS.has(lang) ? 'rtl' : 'ltr' };
  });

const ts = `/**
 * GENERATED by scripts/gen_languages.mjs — do not edit by hand.
 *
 * ${rows.length} languages (one per Ant Design locale). Antd locale objects and
 * dictionaries are loaded through dynamic imports so each language is its own
 * chunk: only the active language plus the English fallback are ever fetched.
 */
import type { Locale } from 'antd/es/locale';

export interface LangOption {
  /** Tag persisted in localStorage, e.g. \`zh-TW\`. */
  value: string;
  /** Endonym shown in the picker (from Intl.DisplayNames, never hand-written). */
  label: string;
  /** English name for logs and coverage reports. */
  english: string;
  /** dayjs locale code for date/relative-time formatting. */
  dayjs: string;
  dir: 'ltr' | 'rtl';
  /** Lazily load the antd component locale + this language's dictionary. */
  load: () => Promise<{ antd: Locale; dict: Record<string, string> }>;
  /** Lazily register the dayjs locale (date pickers, "3 hours ago"). */
  dayjsLoad: () => Promise<unknown>;
}

const load = (
  antd: () => Promise<{ default: Locale }>,
  dict: () => Promise<{ dict: Record<string, string> }>,
) => async () => {
  const [a, d] = await Promise.all([antd(), dict()]);
  return { antd: a.default, dict: d.dict };
};

export const LANGS: LangOption[] = [
${rows.map((r) => `  {
    value: '${r.value}', label: ${JSON.stringify(r.label)}, english: ${JSON.stringify(r.english)},
    dayjs: '${r.dayjs}', dir: '${r.dir}',
    load: load(() => import('antd/locale/${r.antd}'), () => import('./locales/${r.value}')),
    dayjsLoad: () => import('dayjs/locale/${r.dayjs}'),
  },`).join('\n')}
];

export const DEFAULT_LANG = 'en-US';

/** Resolve a browser tag against the available set (zh-Hans-CN → zh-CN). */
export function matchLang(tag: string | undefined | null): string | undefined {
  if (!tag) return undefined;
  const norm = tag.replace(/_/g, '-').toLowerCase();
  const exact = LANGS.find((l) => l.value.toLowerCase() === norm);
  if (exact) return exact.value;
  const base = norm.split('-')[0];
  return LANGS.find((l) => l.value.toLowerCase().split('-')[0] === base)?.value;
}

export const isRTL = (value: string) =>
  LANGS.find((l) => l.value === value)?.dir === 'rtl';
`;

fs.writeFileSync(path.join(REPO, 'web/src/i18n/languages.ts'), ts, 'utf8');
fs.writeFileSync(path.join(REPO, 'web/src/i18n/languages.json'),
  JSON.stringify(rows, null, 2) + '\n', 'utf8');

console.log(`generated ${rows.length} languages`);
console.log('rtl:', rows.filter((r) => r.dir === 'rtl').map((r) => r.value).join(', '));
console.log('dayjs=en fallback:', rows.filter((r) => r.dayjs === 'en' && r.value !== 'en-US')
  .map((r) => r.value).join(', ') || 'none');
console.log('first 5:', rows.slice(0, 5).map((r) => `${r.value}=${r.label}`).join(' | '));
console.log('last 5:', rows.slice(-5).map((r) => `${r.value}=${r.label}`).join(' | '));
