"""Merge the translation fragments into per-language dictionaries.

Source of truth
---------------
`web/src/i18n/parts/*.json`   authored copy — `{"key": {"zh": ..., "en": ...}}`
`web/src/i18n/catalog/*.json` translations for the other languages —
                              `{"key": "text"}` (flat, one file per locale)
`web/src/i18n/languages.json` the language list (generated once, checked in)

Fallback chain per key:  catalog[lang] → zh (for other Chinese variants) →
en (for everything else).  A language therefore never renders a raw key even
while its catalog is still incomplete — the coverage report says how complete
it is.

Generated output: `web/src/i18n/locales/<lang>.ts`, each exporting `dict`.
They are loaded through dynamic imports (see languages.ts), so every language
is its own bundle chunk and nothing is shipped eagerly.

Usage
-----
    python scripts/merge_i18n.py              # write the locale files
    python scripts/merge_i18n.py --check      # verify they are up to date
    python scripts/merge_i18n.py --coverage   # translation coverage table
    python scripts/merge_i18n.py --strict     # exit 1 if any language < 100%
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
WEB = REPO / "web"
I18N = WEB / "src" / "i18n"
PARTS = I18N / "parts"
CATALOG = I18N / "catalog"
LOCALES = I18N / "locales"
LANGUAGES = I18N / "languages.json"
AUTHORED = {"en-US", "zh-CN"}
# A serialized object/array — i.e. a model echoing the request shape
# (``{"en": "…"}``). Plain copy that merely starts with a placeholder
# (``{n} Dateien``) must NOT be filtered out.
NASTY = re.compile(r"""^\s*[\[{]\s*["']""")

PLACEHOLDER = re.compile(r"\{([a-zA-Z0-9_]+)\}")

HEADER = """/**
 * GENERATED by `scripts/merge_i18n.py` from web/src/i18n/parts/*.json and
 * web/src/i18n/catalog/<lang>.json — do not edit by hand.
 *
 * {title} — {count} keys
 */

export const dict: Record<string, string> = {{
"""


def load_parts() -> dict[str, dict[str, str]]:
    """Authored copy: every key with its zh + en text."""
    entries: dict[str, dict[str, str]] = {}
    for path in sorted(PARTS.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        for key, pair in data.items():
            if key in entries and entries[key] != pair:
                raise SystemExit(
                    f"conflict: {key} defined in two fragments with different text\n"
                    f"  {entries[key]}\n  {pair}")
            entries[key] = pair
    return entries


def load_catalog(lang: str) -> dict[str, str]:
    """Translations for a language. The authored columns (zh-CN/en-US) have no
    catalog: their text comes from parts/*.json, and a catalog there could only
    shadow the source. Values that are not plain non-empty strings are ignored
    (a model once echoed a nested object, which rendered as {'en': '...'})."""
    if lang in AUTHORED:
        return {}
    path = CATALOG / f"{lang}.json"
    if not path.exists():
        return {}
    raw = json.loads(path.read_text(encoding="utf-8"))
    out: dict[str, str] = {}
    for key, value in raw.items():
        if not isinstance(value, str) or not value.strip():
            continue
        if NASTY.match(value):
            continue
        out[key] = value
    return out


def fallback_for(lang: str) -> str:
    """Which authored column backs this language when the catalog is silent."""
    return "zh" if lang.startswith("zh") else "en"


def build(entries: dict[str, dict[str, str]], lang: str, catalog: dict[str, str]) -> dict[str, str]:
    back = fallback_for(lang)
    out: dict[str, str] = {}
    seen = set()
    for key, pair in entries.items():
        text = catalog.get(key)
        if text is None or not str(text).strip():
            text = pair[back]
        out[key] = text
        if key in catalog:
            seen.add(key)
    return out


def check_placeholders(key: str, source: str, translated: str) -> list[str]:
    want = sorted(PLACEHOLDER.findall(source))
    got = sorted(PLACEHOLDER.findall(translated))
    if want != got:
        return [f"{key}: placeholders {want} -> {got}"]
    return []


def check_consistent_mapping(entries: dict[str, dict[str, str]]) -> list[str]:
    """Same English word translated two different ways → report it.

    Reverse maps only, so legitimately different source words don't collide.
    """
    problems: list[str] = []
    en_to_zh: dict[str, set[str]] = {}
    zh_to_en: dict[str, set[str]] = {}
    for pair in entries.values():
        zh, en = pair.get("zh", ""), pair.get("en", "")
        if not zh or not en:
            continue
        en_to_zh.setdefault(en, set()).add(zh)
        zh_to_en.setdefault(zh, set()).add(en)

    def same_word(group: set[str]) -> bool:
        low = {t.lower().rstrip("s") for t in group}
        return len(low) == 1

    for en, zhs in sorted(en_to_zh.items()):
        if len(zhs) > 1 and not same_word(zhs):
            problems.append(f"en->zh: {en!r} maps to {sorted(zhs)}")
    for zh, ens in sorted(zh_to_en.items()):
        if len(ens) > 1 and not same_word(ens):
            problems.append(f"zh->en: {zh!r} maps to {sorted(ens)}")
    return problems


def render(dictionary: dict[str, str], title: str) -> str:
    lines = [HEADER.format(title=title, count=len(dictionary))]
    for key in sorted(dictionary):
        text = dictionary[key].replace("\\", "\\\\").replace("'", "\\'")
        text = text.replace("\n", "\\n")
        lines.append(f"  '{key}': '{text}',\n")
    lines.append("};\n")
    return "".join(lines)


def main() -> int:
    args = set(sys.argv[1:])
    entries = load_parts()
    languages = json.loads(LANGUAGES.read_text(encoding="utf-8"))

    if "--coverage" in args:
        total = len(entries)
        print(f"{'language':<10} {'english':<22} {'done':>6}/{total:<6} {'pct':>6}")
        for lang in languages:
            cat = load_catalog(lang["value"])
            if lang["value"] == "zh-CN":      # authored source, not a catalog
                print(f"{lang['value']:<10} {lang['english'][:21]:<22} {total:>6}/{total:<6} 100.0% (source)")
                continue
            done = sum(1 for k in entries if k in cat and str(cat[k]).strip())
            print(f"{lang['value']:<10} {lang['english'][:21]:<22} {done:>6}/{total:<6} "
                  f"{done / total * 100:>5.1f}%")
        return 0

    warnings = check_consistent_mapping(entries)
    if warnings and "--strict" not in args:
        print("warnings (same idea, two wordings):")
        for w in warnings:
            print("  - " + w)

    pending: list[tuple[Path, str]] = []
    incomplete = []
    for lang in languages:
        value = lang["value"]
        catalog = load_catalog(value)
        dictionary = build(entries, value, catalog)

        problems = []
        for key, text in catalog.items():
            if key not in entries:
                problems.append(f"{key}: not in any fragment (stale?).")
                continue
            problems += check_placeholders(key, entries[key].get(fallback_for(value), ""), str(text))
        for problem in problems:
            print(f"  ! {value} {problem}")
        if problems and "--strict" in args:
            return 2

        done = len(entries) if value in AUTHORED else sum(
            1 for k in entries if k in catalog and str(catalog[k]).strip())
        if done < len(entries):
            incomplete.append((value, done, len(entries)))

        title = f"{lang['english']}"
        pending.append((LOCALES / f"{value}.ts", render(dictionary, title)))

    if "--check" in args:
        stale = [p.name for p, expected in pending
                 if not p.exists() or p.read_text(encoding="utf-8") != expected]
        if stale:
            print(f"{len(stale)} locale file(s) out of date: {', '.join(stale[:8])}"
                  f"{' …' if len(stale) > 8 else ''}")
            return 1
        print(f"locale files are up to date ({len(pending)} languages)")
        return 0

    LOCALES.mkdir(parents=True, exist_ok=True)
    for path, content in pending:
        path.write_text(content, encoding="utf-8", newline="\n")

    print(f"{len(entries)} keys × {len(languages)} languages "
          f"from {len(list(PARTS.glob('*.json')))} fragments "
          f"+ {len(list(CATALOG.glob('*.json')))} catalogs")
    if incomplete:
        print(f"incomplete catalogs ({len(incomplete)}): " + ", ".join(
            f"{v} {d}/{t}" for v, d, t in sorted(incomplete)[:12])
            + (" …" if len(incomplete) > 12 else ""))
    if "--strict" in args and incomplete:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
